[[devices]]
id = "goodwe1"
type = "goodwe_sems"
label = "GoodWe DNS-5000"
account = "david.rubert@gmail.com"
password = "CmTv6QB2bhq8Tu@"
station_id = "9064e0e2-5528-4415-b603-b6533b551989"
listen_seconds = 30

[[devices]]
id = "victron1"
type = "victron"
label = "Inversor Goodwe"
ip = "192.168.5.48"
listen_seconds = 5

[[devices.samples]]
id = "red"
label = "Iberdrola"
topic = "system/0/Ac/Grid/L1/Power"
digits = 1

[[devices.samples]]
id = "consumo"
label = "Consumo casa"
topic = "system/0/Ac/Consumption/L1/Power"
digits = 1

[[devices.samples]]
id = "cargas-criticas"
label = "Cargas críticas"
topic = "system/0/Ac/ConsumptionOnOutput/L1/Power"
digits = 1

[[devices.samples]]
id = "fv"
label = "Producción FV"
topics = [
  "system/0/Ac/PvOnOutput/L1/Power",
  "pvinverter/31/Ac/Power",
]
digits = 1

[[devices.samples]]
id = "bateria"
label = "Batería"
topic = "system/0/Dc/Battery/Power"
multiplier = -1
digits = 1

[[devices.samples]]
id = "bateria-tension"
label = "Tensión batería"
topic = "system/0/Dc/Battery/Voltage"
digits = 2

[[devices.samples]]
id = "bateria-corriente"
label = "Corriente batería"
topic = "system/0/Dc/Battery/Current"
digits = 2

[[devices.samples]]
id = "bateria-soc"
label = "SOC batería"
topic = "battery/512/Soc"
digits = 1

[[devices]]
id = "apsystems1"
type = "apsystems"
label = "Microinversor APSystems 1"
ip = "192.168.5.42"
port = 8050

[[devices]]
id = "apsystems2"
type = "apsystems"
label = "Microinversor APSystems 2"
ip = "192.168.5.46"
port = 8050

[[devices]]
id = "apsystems3"
type = "apsystems"
label = "Microinversor APSystems 3"
ip = "192.168.5.43"
port = 8050
